version: '3.3'
services:
  elasticsearch:
    build: .
    ports:
      - "9200:9200"
    expose:
      - 9300
    environment:
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data
  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./dist:/usr/share/nginx/html

volumes:
  es-data:
    driver: local
